"""MongoDB integrations for Microsoft Agent Framework."""

from .errors import (
    MongoDBAuthorizationError,
    MongoDBCapabilityError,
    MongoDBConfigurationError,
    MongoDBEmbeddingError,
    MongoDBEmbeddingGenerationError,
    MongoDBFilterTranslationError,
    MongoDBIndexError,
    MongoDBIndexFailedError,
    MongoDBIndexMismatchError,
    MongoDBIndexMissingError,
    MongoDBIndexNotReadyError,
    MongoDBIntegrationError,
    MongoDBMappingError,
    MongoDBPersistenceError,
    MongoDBRetrievalError,
    MongoDBTimeoutError,
    MongoDBTransientPersistenceError,
    MongoDBTransientRetrievalError,
)
from .history import MongoDBHistoryProvider, MongoDBHistoryProviderOptions
from .memory import MemoryMetadata, MemoryMetadataPage, MongoDBMemoryContextProvider
from .rag import (
    AndFilter,
    EqualFilter,
    GreaterThanFilter,
    GreaterThanOrEqualFilter,
    InFilter,
    LessThanFilter,
    LessThanOrEqualFilter,
    MongoDBFilter,
    MongoDBRAGContextProvider,
    MongoDBRAGParentOptions,
    MongoDBRAGProvider,
    MongoDBRAGProviderOptions,
    MongoDBRAGResult,
    MongoDBRAGSearchOptions,
    MongoDBSearchMode,
    NotEqualFilter,
    NotInFilter,
    OrFilter,
)

__all__ = [
    "AndFilter",
    "EqualFilter",
    "GreaterThanFilter",
    "GreaterThanOrEqualFilter",
    "InFilter",
    "LessThanFilter",
    "LessThanOrEqualFilter",
    "MongoDBAuthorizationError",
    "MongoDBCapabilityError",
    "MongoDBConfigurationError",
    "MongoDBEmbeddingError",
    "MongoDBEmbeddingGenerationError",
    "MongoDBFilter",
    "MongoDBFilterTranslationError",
    "MongoDBIndexError",
    "MongoDBIndexFailedError",
    "MongoDBIndexMismatchError",
    "MongoDBIndexMissingError",
    "MongoDBIndexNotReadyError",
    "MongoDBIntegrationError",
    "MongoDBMappingError",
    "MongoDBHistoryProvider",
    "MongoDBHistoryProviderOptions",
    "MongoDBMemoryContextProvider",
    "MongoDBPersistenceError",
    "MongoDBRAGContextProvider",
    "MongoDBRAGParentOptions",
    "MongoDBRAGProvider",
    "MongoDBRAGProviderOptions",
    "MongoDBRAGResult",
    "MongoDBRAGSearchOptions",
    "MongoDBRetrievalError",
    "MongoDBSearchMode",
    "MongoDBTimeoutError",
    "MongoDBTransientPersistenceError",
    "MongoDBTransientRetrievalError",
    "MemoryMetadata",
    "MemoryMetadataPage",
    "NotEqualFilter",
    "NotInFilter",
    "OrFilter",
]
