"""MongoDB integrations for Microsoft Agent Framework."""

from importlib.metadata import version as _distribution_version

from .checkpointing import (
    MongoDBCheckpointClearResult,
    MongoDBCheckpointNotFoundError,
    MongoDBCheckpointPage,
    MongoDBCheckpointStorage,
    MongoDBCheckpointStorageOptions,
)
from .errors import (
    MongoDBAuthorizationError,
    MongoDBCapabilityError,
    MongoDBConcurrencyError,
    MongoDBConfigurationError,
    MongoDBEmbeddingError,
    MongoDBEmbeddingGenerationError,
    MongoDBFilterTranslationError,
    MongoDBIndexError,
    MongoDBIndexFailedError,
    MongoDBIndexMismatchError,
    MongoDBIndexMissingError,
    MongoDBIndexNotReadyError,
    MongoDBIntegrationError,
    MongoDBMappingError,
    MongoDBPersistenceError,
    MongoDBRetrievalError,
    MongoDBSerializationError,
    MongoDBTimeoutError,
    MongoDBTransientPersistenceError,
    MongoDBTransientRetrievalError,
)
from .history import MongoDBHistoryProvider, MongoDBHistoryProviderOptions
from .indexing import (
    MongoDBIndexDefinition,
    MongoDBIndexResult,
    MongoDBIndexState,
    MongoDBRegularIndexDefinition,
    MongoDBSearchIndexDefinition,
    MongoDBVectorIndexDefinition,
)
from .memory import MemoryMetadata, MemoryMetadataPage, MongoDBMemoryContextProvider
from .rag import (
    AndFilter,
    EqualFilter,
    GreaterThanFilter,
    GreaterThanOrEqualFilter,
    InFilter,
    LessThanFilter,
    LessThanOrEqualFilter,
    MongoDBFilter,
    MongoDBRAGContextProvider,
    MongoDBRAGParentOptions,
    MongoDBRAGProvider,
    MongoDBRAGProviderOptions,
    MongoDBRAGResult,
    MongoDBRAGSearchOptions,
    MongoDBSearchMode,
    NotEqualFilter,
    NotInFilter,
    OrFilter,
)
from .session_store import MongoDBSessionStore, MongoDBSessionStoreOptions, MongoDBVersionedSession

__version__ = _distribution_version("agent-framework-mongodb")

__all__ = [
    "AndFilter",
    "EqualFilter",
    "GreaterThanFilter",
    "GreaterThanOrEqualFilter",
    "InFilter",
    "LessThanFilter",
    "LessThanOrEqualFilter",
    "MongoDBCheckpointNotFoundError",
    "MongoDBCheckpointClearResult",
    "MongoDBCheckpointPage",
    "MongoDBCheckpointStorage",
    "MongoDBCheckpointStorageOptions",
    "MongoDBAuthorizationError",
    "MongoDBCapabilityError",
    "MongoDBConfigurationError",
    "MongoDBConcurrencyError",
    "MongoDBEmbeddingError",
    "MongoDBEmbeddingGenerationError",
    "MongoDBFilter",
    "MongoDBFilterTranslationError",
    "MongoDBIndexError",
    "MongoDBIndexDefinition",
    "MongoDBIndexFailedError",
    "MongoDBIndexMismatchError",
    "MongoDBIndexMissingError",
    "MongoDBIndexNotReadyError",
    "MongoDBIndexResult",
    "MongoDBIndexState",
    "MongoDBIntegrationError",
    "MongoDBMappingError",
    "MongoDBHistoryProvider",
    "MongoDBHistoryProviderOptions",
    "MongoDBMemoryContextProvider",
    "MongoDBPersistenceError",
    "MongoDBRAGContextProvider",
    "MongoDBRAGParentOptions",
    "MongoDBRAGProvider",
    "MongoDBRAGProviderOptions",
    "MongoDBRAGResult",
    "MongoDBRAGSearchOptions",
    "MongoDBRegularIndexDefinition",
    "MongoDBRetrievalError",
    "MongoDBSerializationError",
    "MongoDBSearchIndexDefinition",
    "MongoDBSearchMode",
    "MongoDBSessionStore",
    "MongoDBSessionStoreOptions",
    "MongoDBVersionedSession",
    "MongoDBTimeoutError",
    "MongoDBTransientPersistenceError",
    "MongoDBTransientRetrievalError",
    "MongoDBVectorIndexDefinition",
    "MemoryMetadata",
    "MemoryMetadataPage",
    "NotEqualFilter",
    "NotInFilter",
    "OrFilter",
    "__version__",
]
