name: Dependency review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d3f86a106a0bac45b974a628896c90dbdf5c8093 # actions/checkout v4
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # actions/dependency-review-action v4
